apiVersion: autoscaling/v2beta2 #Hescalado horizontal
kind: HorizontalPodAutoscaler
metadata:
  name: mi-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-api-php
  minReplicas: 2 #Minimo de replicas
  maxReplicas: 10 #Maximo de replicas
  metrics: 
  - type: Resource #Tipo de metrica
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50 
